(in-package #:clecto)

;;; The adapter protocol: a thin set of generic functions that describe
;;; how to dispatch SQL to a particular database. Adapter instances are
;;; just values — any state (a connection) is held as a slot, never as
;;; module-global mutation.

(defclass adapter () ()
  (:documentation "Base class for all DB adapters."))

(defgeneric adapter-execute (adapter sql params)
  (:documentation
   "Execute SQL with positional PARAMS. Return a list of plists (one per row).
PARAMS is a list of values in the order their placeholders appear."))

(defgeneric adapter-execute-returning (adapter sql params)
  (:documentation
   "Execute SQL that mutates and return (values rows-affected last-insert-id).
For RETURNING-style adapters this can be specialized to return rows instead."))

(defun lispify-column (name)
  "DB column name -> keyword: \"user_id\" -> :USER-ID."
  (alexandria:make-keyword
   (string-upcase (substitute #\- #\_ (string name)))))

(defun sqlify-column (name)
  "Keyword -> DB column name: :user-id -> \"user_id\"."
  (substitute #\_ #\- (string-downcase (string name))))

(defgeneric adapter-quote-identifier (adapter name)
  (:documentation "Quote a column/table identifier per the dialect.")
  (:method ((a adapter) name)
    (format nil "\"~a\"" (sqlify-column name))))

(defgeneric adapter-placeholder (adapter index)
  (:documentation "Render the Nth (1-based) parameter placeholder.")
  (:method ((a adapter) index)
    (declare (ignore index))
    "?"))

(defgeneric adapter-last-insert-id (adapter)
  (:documentation "Return the ID generated by the most recent INSERT."))
