(in-package #:clecto)

;;; The adapter protocol: a thin set of generic functions that describe
;;; how to dispatch SQL to a particular database. Adapter instances are
;;; just values — any state (a connection) is held as a slot, never as
;;; module-global mutation.

(defclass adapter () ()
  (:documentation "Base class for all DB adapters."))

(defgeneric adapter-execute (adapter sql params)
  (:documentation
   "Execute SQL with positional PARAMS. Return a list of plists (one per row).
PARAMS is a list of values in the order their placeholders appear."))

(defgeneric adapter-execute-returning (adapter sql params)
  (:documentation
   "Execute SQL that mutates and return (values rows-affected last-insert-id).
For RETURNING-style adapters this can be specialized to return rows instead."))

(defvar *lispify-cache* (make-hash-table :test 'equal)
  "String -> keyword cache so the same DB column name never re-interns.
Bounds memory growth to the set of distinct column names actually emitted
by the database (developer-controlled in practice).")

(defun lispify-column (name)
  "DB column name -> keyword: \"user_id\" -> :USER-ID. Cached to avoid
unbounded keyword interning on hot query paths."
  (let ((s (string name)))
    (or (gethash s *lispify-cache*)
        (setf (gethash s *lispify-cache*)
              (alexandria:make-keyword
               (string-upcase (substitute #\- #\_ s)))))))

(defun sqlify-column (name)
  "Keyword -> DB column name: :user-id -> \"user_id\"."
  (substitute #\_ #\- (string-downcase (string name))))

(defun split-qualified (name)
  "Return (values qualifier base) for :users.id, or (values nil base)."
  (let* ((s (sqlify-column name))
         (dot (position #\. s)))
    (if dot
        (values (subseq s 0 dot) (subseq s (1+ dot)))
        (values nil s))))

(defun escape-identifier-body (s)
  "Escape the inside of a double-quoted SQL identifier: \"\"\"\" doubles the
quote, NUL is rejected outright."
  (when (find #\Nul s)
    (error "Identifier contains NUL byte: ~s" s))
  (if (find #\" s)
      (with-output-to-string (out)
        (loop for c across s do
          (if (char= c #\") (write-string "\"\"" out) (write-char c out))))
      s))

(defgeneric adapter-quote-identifier (adapter name)
  (:documentation "Quote a column/table identifier per the dialect.
Handles qualified names like :users.id -> \"users\".\"id\".")
  (:method ((a adapter) name)
    (multiple-value-bind (q c) (split-qualified name)
      (if q (format nil "\"~a\".\"~a\""
                    (escape-identifier-body q)
                    (escape-identifier-body c))
            (format nil "\"~a\"" (escape-identifier-body c))))))

(defgeneric adapter-placeholder (adapter index)
  (:documentation "Render the Nth (1-based) parameter placeholder.")
  (:method ((a adapter) index)
    (declare (ignore index))
    "?"))

(defgeneric adapter-last-insert-id (adapter)
  (:documentation "Return the ID generated by the most recent INSERT.
Adapters that always use RETURNING may signal an error here."))

(defgeneric adapter-supports-returning-p (adapter)
  (:documentation
   "T if the adapter prefers `INSERT ... RETURNING ...` to recover an
auto-generated PK (and other server-defaulted columns). The repo uses
this to choose between RETURNING and a last-insert-id roundtrip.")
  (:method ((a adapter)) nil))

(defgeneric adapter-begin (adapter)
  (:documentation "Open a transaction. Idempotent across nesting via savepoints."))

(defgeneric adapter-commit (adapter)
  (:documentation "Commit the most recent BEGIN or RELEASE a savepoint."))

(defgeneric adapter-rollback (adapter)
  (:documentation "Roll back the most recent BEGIN or ROLLBACK TO savepoint."))

(define-condition rollback () ()
  (:documentation
   "Signaled to abort a repo-transaction. The transaction body sees no
condition; any returned value is discarded and the txn is rolled back."))

(defgeneric adapter-translate-constraint-error (adapter condition constraints)
  (:documentation
   "Inspect a DB error condition against CONSTRAINTS (a list of CONSTRAINT
records). Return (values field message) when the error matches, or NIL.
The default never matches; each adapter specializes for its dialect.")
  (:method ((a adapter) c constraints)
    (declare (ignore c constraints))
    nil))
